# Generated by Django 4.2.4 on 2024-07-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_user_groups_group_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='enterprise',
            new_name='Enterprise',
        ),
    ]
