# Generated by Django 4.2.4 on 2024-07-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_enterprise_group_enterprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='Enterprise',
            new_name='enterprise',
        ),
    ]
